### ISSUE TITLE
Status Code: 500 Response: undefined posting to homebridge-camera-ffmpeg

### ISSUE THREAD

**Issue by Tesla-P100FX** [kushagharahi/homebridge-dahua-alerts#18]
Getting error Dahua Alerts Bridgedahua-alertsERRORError when posting reset video motion to homebridge-camera-ffmpeg - Status Code: 500 Response: undefined

Camera config is (Just showing one camera) 

accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "porthttp": 8088,
            "localhttp": true,
            "cameras": [
                {
                    "name": "Driveway",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.151:554/cam/realmonitor?channel=1&subtype=1"
                    }

{

Alert config is 

    "accessories": [],
    "platforms": [
        {
            "platform": "dahua-alerts",
            "host": "10.0.0.151",
            "user": "admin",
            "pass": "pass",
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "Driveway"
                },
                {
                    "index": 1,
                    "cameraName": "Sport Court"
                },
                {
                    "index": 2,
                    "cameraName": "Fire Pit"
                },
                {
                    "index": 3,
                    "cameraName": "South Steps"
                },
                {
                    "index": 4,
                    "cameraName": "Inside Garage"
                },
                {
                    "index": 5,
                    "cameraName": "Front Door "
                },
                {
                    "index": 6,
                    "cameraName": "Covered Table Area "
                },
                {
                    "index": 7,
                    "cameraName": "North Steps"
                }
            ],
            "homebridgeCameraFfmpegHttpPort": 57826,
            "useHttp": true
        }
    ]

i am unclear what http port to point it to.   8080, 554 or 57826 is the bridge port that Homebridge says its running on 

running 1.1.5 

Homebridge 1.3.4

Node 14.17.2

**Comment by kushagharahi** [comment]
Hey there,

Can you try setting `homebridgeCameraFfmpegHttpPort` to 8088?

It needs to be the same as `porthttp` on your ffmpeg config 😄

**Comment by Tesla-P100FX** [comment]
OK did that but now it says

MDahua Alerts Bridgedahua-alertsReset motion for Sport Court posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }

7/24/2021, 9:44:55 AMDahua Alerts Bridgedahua-alertsERRORError when posting reset video motion to homebridge-camera-ffmpeg - Status Code: 500 Response: undefined

**Comment by Tesla-P100FX** [comment]
Do I uncheck the "enable Motion Sensor" in the ffmpg config - is that duplicative with your bridge

**Comment by kushagharahi** [comment]
Can you try restarting homebridge please?

**Comment by Tesla-P100FX** [comment]
same 

MDahua Alerts Bridgedahua-alertsERRORError when posting reset video motion to homebridge-camera-ffmpeg - Status Code: 500 Response: undefined

**Comment by kushagharahi** [comment]
Could you post your full camera (ffmpeg) config and full dahua-alerts config? I have a hunch about what's going on.

Careful not to post any passwords!

**Comment by Tesla-P100FX** [comment]
I love that you have a hunch! I’ll do this when I get back home
In an hour or so!


Thanks

Rich

Wear a mask 😷 and be safe

Sent from my Phone 📞, please excuse typos and amusing autocorrects



________________________________

**Comment by Tesla-P100FX** [comment]
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "porthttp": 8088,
            "localhttp": false,
            "cameras": [
                {
                    "name": "Driveway",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxx@10.0.0.151:554/cam/realmonitor?channel=1&subtype=1"
                    }
                },
                {
                    "name": "Sport Court",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxx@10.0.0.151:554/cam/realmonitor?channel=2&subtype=1"
                    }
                },
                {
                    "name": "Fire Pit",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxxx@10.0.0.151:554/cam/realmonitor?channel=3&subtype=1"
                    }
                },
                {
                    "name": "South Steps",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxx@10.0.0.151:554/cam/realmonitor?channel=4&subtype=1"
                    }
                },
                {
                    "name": "Inside Garage",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxx@10.0.0.151:554/cam/realmonitor?channel=5&subtype=1"
                    }
                },
                {
                    "name": "Front Door",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxx@10.0.0.151:554/cam/realmonitor?channel=6&subtype=1"
                    }
                },
                {
                    "name": "Covered Table Area",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxx@10.0.0.151:554/cam/realmonitor?channel=7&subtype=1"
                    }
                },
                {
                    "name": "North Steps",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:xxxx!@10.0.0.151:554/cam/realmonitor?channel=8&subtype=1"
                    }
                }
            ]
        }
    ]
}


       {
            "platform": "dahua-alerts",
            "host": "10.0.0.151",
            "user": "admin",
            "pass": "xxxx",
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "Driveway"
                },
                {
                    "index": 1,
                    "cameraName": "Sport Court"
                },
                {
                    "index": 2,
                    "cameraName": "Fire Pit"
                },
                {
                    "index": 3,
                    "cameraName": "South Steps"
                },
                {
                    "index": 4,
                    "cameraName": "Inside Garage"
                },
                {
                    "index": 5,
                    "cameraName": "Front Door "
                },
                {
                    "index": 6,
                    "cameraName": "Covered Table Area "
                },
                {
                    "index": 7,
                    "cameraName": "North Steps"
                }
            ],
            "homebridgeCameraFfmpegHttpPort": 8088,
            "useHttp": true
        }
    ]
}

**Comment by kushagharahi** [comment]
Can you change `"localhttp": false,` from false to true? In your original post it was true. 

Also in your dahua cameras config some of the names have spaces at the end while the ffmpeg cameras do not. Such as:
```

            {
                "index": 5,
                "cameraName": "Front Door "
            },
            {
                "index": 6,
                "cameraName": "Covered Table Area "
            },
```


Could you please remove the extra space at the end of these names?

**Comment by Tesla-P100FX** [comment]
I fixed thos things but still getting the following:

Configuration change
7/24/2021, 2:00:39 PMDahua Alerts BridgeLoaded plugin 'homebridge-dahua-alerts'
7/24/2021, 2:00:39 PMDahua Alerts BridgeLoading 1 platforms...
7/24/2021, 2:00:39 PMDahua Alerts BridgeBridge is running on port 56826.
7/24/2021, 2:00:56 PMDahua Alerts Bridgedahua-alertsReset motion for Driveway posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/24/2021, 2:01:19 PMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/24/2021, 2:02:06 PMDahua Alerts Bridgedahua-alertsReset motion for North Steps posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/24/2021, 2:02:09 PMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }

**Comment by kushagharahi** [comment]
Those aren’t errors, looks to me as if it’s working. Is there a specific issue you're facing?

**Comment by Tesla-P100FX** [comment]
It never shows motion in the HomeKit app so I can't use it as a trigger

**Comment by Tesla-P100FX** [comment]
Maybe i have the wrong sensor  configured on my phone.   if i go to one of the motion Sensors in Homekit it says the bridge is 
Camera FFMP Bridge.  Shouldn't it say Dahua Alerts Bridge?

**Comment by kushagharahi** [comment]
The motion sensors are set by the ffmpeg app, this app just triggers the motion alerts

**Comment by kushagharahi** [comment]
![05854DE9-DB01-45DA-AC9F-986A47687AAB](https://user-images.githubusercontent.com/3326002/126883031-5521e307-e1e8-4df1-951c-ab07dfe80f4b.png)
If you want notifications to appear on your phone you have to enable notifications on the camera. Home settings > Cameras and doorbells

**Comment by Tesla-P100FX** [comment]
Got it!   Thanks for all your assistance today.   Still testing but it seems like we everything set right😀


Thanks

Rich

Wear a mask 😷 and be safe

Sent from my Phone 📞, please excuse typos and amusing autocorrects



________________________________

**Comment by kushagharahi** [comment]
Awesome! Glad to hear that. I'm going to close this issue.

Feel free to reopen this issue if you continue having problems related to this or a new issue for a new problem!
