### ISSUE TITLE
Protocol "https:" not supported. Expected "http:" and only getting reset motion alerts

### ISSUE THREAD

**Issue by Tesla-P100FX** [kushagharahi/homebridge-dahua-alerts#19]
Changed the IP and HTTPS on 443 and now getting 

7/25/2021, 7:21:36 PMDahua Alerts Bridge starting
7/25/2021, 7:21:41 PMDahua Alerts BridgeLoaded plugin 'homebridge-dahua-alerts'
7/25/2021, 7:21:41 PMDahua Alerts BridgeLoading 1 platforms...
7/25/2021, 7:21:41 PMDahua Alerts BridgeBridge is running on port 56826.
7/25/2021, 7:21:41 PMDahua Alerts BridgeERRORTypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:159:11)
    at Object.request (https.js:333:10)
    at RedirectableRequest._performRequest (/var/lib/hoobs/dahuaalertsbridge/node_modules/follow-redirects/index.js:169:24)
    at RedirectableRequest._processResponse (/var/lib/hoobs/dahuaalertsbridge/node_modules/follow-redirects/index.js:260:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/var/lib/hoobs/dahuaalertsbridge/node_modules/follow-redirects/index.js:50:10)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at ClientRequest.emit (domain.js:470:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)

Config is 👍 

{
    "accessories": [],
    "platforms": [
        {
            "platform": "dahua-alerts",
            "host": "10.0.0.153",
            "user": "admin",
            "pass": "pass",
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "Driveway"
                },
                {
                    "index": 1,
                    "cameraName": "Sport Court"
                },
                {
                    "index": 2,
                    "cameraName": "Fire Pit"
                },
                {
                    "index": 3,
                    "cameraName": "South Steps"
                },
                {
                    "index": 4,
                    "cameraName": "Inside Garage"
                },
                {
                    "index": 5,
                    "cameraName": "Front Door"
                },
                {
                    "index": 6,
                    "cameraName": "Covered Table Area"
                },
                {
                    "index": 7,
                    "cameraName": "North Steps"
                }
            ],
            "homebridgeCameraFfmpegHttpPort": 8088,
            "useHttp": true
        }
    ]
}

**Comment by kushagharahi** [comment]
Can you try setting `useHttp` to false?

**Comment by Tesla-P100FX** [comment]
So let me send you everything agian.  Its set to false now and i get this:

7/26/2021, 8:35:17 AMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/26/2021, 8:35:45 AMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/26/2021, 8:36:02 AMDahua Alerts Bridgedahua-alertsReset motion for Driveway posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/26/2021, 8:36:28 AMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/26/2021, 8:37:03 AMDahua Alerts Bridgedahua-alertsReset motion for North Steps posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/26/2021, 8:37:20 AMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/26/2021, 8:37:26 AMDahua Alerts Bridgedahua-alertsReset motion for North Steps posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }

So it is "seeing" the alerts but i nver see an alert of my phone.  I have HTTPS Port 443 enabled on the LOREX DVR
and i have Home / Settings / Door Bells and Camera Set to on for each LOREX Camera 

My FFMPG config is 

{
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "name": "Camera FFmpeg",
            "porthttp": 8088,
            "localhttp": true,
            "cameras": [
                {
                    "name": "Driveway",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.153:554/cam/realmonitor?channel=1&subtype=1"
                    }
                },
                {
                    "name": "Sport Court",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.153:554/cam/realmonitor?channel=2&subtype=1"
                    }
                },
                {
                    "name": "Fire Pit",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.153:554/cam/realmonitor?channel=3&subtype=1"
                    }
                },
                {
                    "name": "South Steps",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.153:554/cam/realmonitor?channel=4&subtype=1"
                    }
                },
                {
                    "name": "Inside Garage",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.153:554/cam/realmonitor?channel=5&subtype=1"
                    }
                },
                {
                    "name": "Front Door",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.153:554/cam/realmonitor?channel=6&subtype=1"
                    }
                },
                {
                    "name": "Covered Table Area",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.153:554/cam/realmonitor?channel=7&subtype=1"
                    }
                },
                {
                    "name": "North Steps",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@10.0.0.153:554/cam/realmonitor?channel=8&subtype=1"
                    }
                }
            ]
        }
    ]
}

My alerts settings are 

{
    "accessories": [],
    "platforms": [
        {
            "platform": "dahua-alerts",
            "host": "10.0.0.153",
            "user": "admin",
            "pass": "pass",
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "Driveway",
                    "cameraCredentials": {
                        "host": "10.0.0.153",
                        "user": "admin",
                        "pass": "Ppass"
                    }
                },
                {
                    "index": 1,
                    "cameraName": "Sport Court",
                    "cameraCredentials": {
                        "host": "10.0.0.153",
                        "user": "admin",
                        "pass": "pass"
                    }
                },
                {
                    "index": 2,
                    "cameraName": "Fire Pit",
                    "cameraCredentials": {
                        "host": "10.0.0.153",
                        "user": "admin",
                        "pass": "pass"
                    }
                },
                {
                    "index": 3,
                    "cameraName": "South Steps",
                    "cameraCredentials": {
                        "host": "10.0.0.153",
                        "user": "admin",
                        "pass": "pass"
                    }
                },
                {
                    "index": 4,
                    "cameraName": "Inside Garage",
                    "cameraCredentials": {
                        "host": "10.0.0.153",
                        "user": "admin",
                        "pass": "pass"
                    }
                },
                {
                    "index": 5,
                    "cameraName": "Front Door",
                    "cameraCredentials": {
                        "host": "10.0.0.153",
                        "user": "admin",
                        "pass": "Ppass"
                    }
                },
                {
                    "index": 6,
                    "cameraName": "Covered Table Area",
                    "cameraCredentials": {
                        "host": "10.0.0.153",
                        "user": "admin",
                        "pass": "pass"
                    }
                },
                {
                    "index": 7,
                    "cameraName": "North Steps",
                    "cameraCredentials": {
                        "host": "10.0.0.153",
                        "user": "admin",
                        "pass": "pass"
                    }
                }
            ],
            "homebridgeCameraFfmpegHttpPort": 8088,
            "useHttp": false
        }
    ]
}

i still never get an alert on the phone

I also have a ring camera and Bridge and i do see those alerts

**Comment by kushagharahi** [comment]
Do you have motion alerts enabled on your camera system?

It seems like you have other types of alerts other than motion enabled, so the plugin is detecting when those alerts end and sending stop motion for those cameras to ffmpeg. (it shouldn't do this) Also this means that no alerts would ever be routed to your phone, because motion alerts are disabled. This plugin only routes motion alerts for now. 

Can you post some debug logs?

**Comment by Tesla-P100FX** [comment]
I did turn on Debug in FFMPG  but didn't see any new entries in the log(is it in a separate log file).  I am running on Homebridge 1.3.4.  I did not mention  that each plug in is running in a separate bridge  on my RasberryPi.   Does your alerts plug-in need to be in the same bridge instance as the FFMPG bridge?

**Comment by kushagharahi** [comment]
The communication between dahua-alerts <-> camera-ffmpeg is working fine.

I need you to post logs for dahua-alerts with debug turned on. Not ffmpeg.

Also could you please double check that your cameras have "motion alerts" turned on? This plugin _only_ routes motion alerts, not any other kind of alert.

**Comment by Tesla-P100FX** [comment]
All my cameras are set like this 
![image](https://user-images.githubusercontent.com/68130459/127243234-6f5116bb-2050-43ef-8d28-a6b6134a8c9d.png)

Logging turned on still showing same thing.   

motion for Fire Pit posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/27/2021, 5:08:03 PMDahua Alerts Bridgedahua-alertsReset motion for Driveway posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/27/2021, 5:09:48 PMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/27/2021, 5:10:07 PMDahua Alerts Bridgedahua-alertsReset motion for Driveway posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/27/2021, 5:10:32 PMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/27/2021, 5:10:45 PMDahua Alerts Bridgedahua-alertsReset motion for Driveway posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/27/2021, 5:11:04 PMDahua Alerts Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }

**Comment by kushagharahi** [comment]
Ok. Your camera settings look ok. Those logs however are not debug logs.

You need to run your homebridge with the debug mode flag turned on. Once turned on there will be extra logs.

**Comment by Tesla-P100FX** [comment]
I appreciate you helping me ,   Thankful for you helping me out.   Will turn that on

**Comment by kushagharahi** [comment]
No prob! Without users reporting issues I won't be able to fix them.

**Comment by Tesla-P100FX** [comment]
I’m embarrassed to say I don’t know how to turn on loging for Homebridge all up I can’t see anywhere in the US to do that is there a command line


Thanks

Rich

Wear a mask 😷 and be safe

Sent from my Phone 📞, please excuse typos and amusing autocorrects



________________________________

**Comment by kushagharahi** [comment]
No worries! How are you running Homebridge?

**Comment by Tesla-P100FX** [comment]
Raspberry Pi with Hoobs 4.0 on Homebridge 1.3.4 and nice 14.17.2 [Image.jpeg]

Thanks

Rich

Wear a mask 😷 and be safe

Sent from my Phone 📞, please excuse typos and amusing autocorrects



________________________________

**Comment by kushagharahi** [comment]
I’m not familiar with HOOBS but I’m confident we can figure it out.

I’m assuming you can access the command line/terminal in the HOOBS UI and that’s how you’re getting logs? If so can you run `sudo hbs log -d`

**Comment by Tesla-P100FX** [comment]
Yes  right now it shows

7/30/2021, 2:41:05 PM Camera FFmpeg Bridge dahua-alerts Reset motion for North Steps posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/30/2021, 2:41:07 PM Camera FFmpeg Bridge dahua-alerts Reset motion for Driveway posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/30/2021, 2:41:07 PM Camera FFmpeg Bridge dahua-alerts Reset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }

**Comment by kushagharahi** [comment]
Ok looks like that didn’t do it either. 

On the logs screen do you see a little bug symbol in the upper left after the word “plugins”? If so, click it so that the icon has a check mark. Then wait for new logs to roll in and copy paste that to me. It should look a little different with extra info inbetween the logs you’ve provided.

**Comment by kushagharahi** [comment]
![57DA1AE6-A85A-4F92-AEDC-CB7667E9E9B4](https://user-images.githubusercontent.com/3326002/127716476-8b8d73f6-5fec-452e-b1c3-9cb2f4e1c262.jpeg)

**Comment by Tesla-P100FX** [comment]
Thanks, let me see if I can figure that out

**Comment by Tesla-P100FX** [comment]
Found it thank you😊 logging now

**Comment by Tesla-P100FX** [comment]
Debug is on but get same messages ☹


7/30/2021, 2:55:48 PMCamera FFmpeg Bridgedahua-alertsReset motion for Driveway posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }7/30/2021, 2:55:51 PMCamera FFmpeg Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }7/30/2021, 2:55:52 PMCamera FFmpeg Bridgedahua-alertsReset motion for Fire Pit posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }7/30/2021, 2:56:02 PMCamera FFmpeg Bridgedahua-alertsReset motion for North Steps posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }7/30/2021, 2:56:12 PMCamera FFmpeg Bridgedahua-alertsReset motion for Fire Pit posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }7/30/2021, 2:56:17

**Comment by kushagharahi** [comment]
It looks like it’s after 3pm your time and those logs after pre 3pm looking at the timestamp. Wait for new logs to show up to see if any debug logs roll in too. Ensure the bug symbol is checked when the new logs roll in.

**Comment by Tesla-P100FX** [comment]
Ok tracking now


Thanks

Rich

Wear a mask 😷 and be safe

Sent from my Phone 📞, please excuse typos and amusing autocorrects



________________________________

**Comment by Tesla-P100FX** [comment]
7/30/2021, 3:51:07 PMCamera FFmpeg BridgeInitializing HAP-NodeJS v0.9.4...
7/30/2021, 3:51:09 PMCamera FFmpeg BridgeLoaded plugin 'homebridge-camera-ffmpeg'
7/30/2021, 3:51:09 PMCamera FFmpeg BridgeRegistering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeLoaded plugin 'homebridge-dahua-alerts'
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeLoading 2 platforms...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpeg[Driveway] Configuring cached bridged accessory...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpeg[Sport Court] Configuring cached bridged accessory...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpeg[Fire Pit] Configuring cached bridged accessory...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeRegistering platform 'homebridge-dahua-alerts.dahua-alerts'
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpeg[Inside Garage] Configuring cached bridged accessory...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpeg[Front Door] Configuring cached bridged accessory...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpeg[Covered Table Area] Configuring cached bridged accessory...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpeg[North Steps] Configuring cached bridged accessory...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpeg[South Steps] Configuring cached bridged accessory...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeCamera FFmpegSetting up localhost-only HTTP server on port 8088...
7/30/2021, 3:51:10 PMCamera FFmpeg BridgePreparing Advertiser for 'Camera FFmpeg Bridge E872' using bonjour-hap backend!
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeStarting to advertise 'Camera FFmpeg Bridge E872' using bonjour-hap backend!
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeSetup URI 'X-HM://0023ISYWYNAGF'
7/30/2021, 3:51:10 PMCamera FFmpeg BridgeBridge is running on port 57826.
7/30/2021, 3:51:36 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 8.5C
7/30/2021, 3:51:40 PMCamera FFmpeg Bridgedahua-alertsSocket connection timed out or closed by NVR.
7/30/2021, 3:51:40 PMCamera FFmpeg Bridgedahua-alertsReconnecting in 1s.
7/30/2021, 3:52:01 PMCamera FFmpeg Bridgedahua-alertsResponse recieved: --myboundary
Content-Type: text/plain
Content-Length:76

Code=VideoMotion;action=Stop;index=6;data={
   "SmartMotionEnable" : true
}


7/30/2021, 3:52:01 PMCamera FFmpeg Bridgedahua-alertsVideo Motion Ended on index: 6, mapped to camera Covered Table Area
7/30/2021, 3:52:01 PMCamera FFmpeg BridgeCamera FFmpeg[Covered Table Area] Switch motion detect off.
7/30/2021, 3:52:01 PMCamera FFmpeg Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/30/2021, 3:52:06 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 4C
7/30/2021, 3:52:31 PMCamera FFmpeg Bridgedahua-alertsSocket connection timed out or closed by NVR.
7/30/2021, 3:52:31 PMCamera FFmpeg Bridgedahua-alertsReconnecting in 1s.
7/30/2021, 3:52:33 PMCamera FFmpeg Bridgedahua-alertsResponse recieved: --myboundary
Content-Type: text/plain
Content-Length:76

Code=VideoMotion;action=Stop;index=0;data={
   "SmartMotionEnable" : true
}


7/30/2021, 3:52:33 PMCamera FFmpeg Bridgedahua-alertsVideo Motion Ended on index: 0, mapped to camera Driveway
7/30/2021, 3:52:33 PMCamera FFmpeg BridgeCamera FFmpeg[Driveway] Switch motion detect off.
7/30/2021, 3:52:33 PMCamera FFmpeg Bridgedahua-alertsReset motion for Driveway posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/30/2021, 3:52:36 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 8.5C
7/30/2021, 3:52:52 PMOmnilink Platform BridgeOmniThermostat 6 [Rich's Offic]: 31C; Off
7/30/2021, 3:53:03 PMCamera FFmpeg Bridgedahua-alertsSocket connection timed out or closed by NVR.
7/30/2021, 3:53:03 PMCamera FFmpeg Bridgedahua-alertsReconnecting in 1s.
7/30/2021, 3:53:06 PMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 1C
7/30/2021, 3:53:13 PMCamera FFmpeg Bridgedahua-alertsResponse recieved: --myboundary
Content-Type: text/plain
Content-Length:76

Code=VideoMotion;action=Stop;index=1;data={
   "SmartMotionEnable" : true
}


7/30/2021, 3:53:13 PMCamera FFmpeg Bridgedahua-alertsVideo Motion Ended on index: 1, mapped to camera Sport Court
7/30/2021, 3:53:13 PMCamera FFmpeg BridgeCamera FFmpeg[Sport Court] Switch motion detect off.
7/30/2021, 3:53:13 PMCamera FFmpeg Bridgedahua-alertsReset motion for Sport Court posted to ho

**Comment by Tesla-P100FX** [comment]
Basically this is what it is doing now


7/31/2021, 6:28:42 AMCamera FFmpeg Bridgedahua-alertsVideo Motion Ended on index: 6, mapped to camera Covered Table Area
7/31/2021, 6:28:42 AMCamera FFmpeg BridgeCamera FFmpeg[Covered Table Area] Switch motion detect off.
7/31/2021, 6:28:42 AMCamera FFmpeg Bridgedahua-alertsReset motion for Covered Table Area posted to homebridge-camera-ffmpeg, received { error: false, message: 'Motion switched off.' }
7/31/2021, 6:28:54 AMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 8C
7/31/2021, 6:29:12 **AMCamera FFmpeg Bridgedahua-alertsSocket connection timed out or closed by NVR.
7/31/2021, 6:29:12 AMCamera FFmpeg Bridgedahua-alertsReconnecting in 1s.**
7/31/2021, 6:29:24 AMOmnilink Platform BridgeOmniAuxiliarySensor 16 [Thermostats]: 4.5C
7/31/2021, 6:29:25 AMCamera FFmpeg Bridgedahua-alertsResponse recieved: --myboundary
Content-Type: text/plain
Content-Length:76

Code=VideoMotion;action=Stop;index=6;data={
   "SmartMotionEnable" : true
}

Does this help?

**Comment by kushagharahi** [comment]
Ok -- This issue is because you have Smart Motion Detection enabled. Unfortunately this plugin does not support Smart Motion Detection (including person/vehicle detection). If you disable it I believe you will get regular motion alerts on your devices. I should have caught this when you posted the screenshot of your settings.

Related following feature request: https://github.com/kushagharahi/homebridge-dahua-alerts/issues/15

----

Let me give you some technical information that you may or may not care about.

This plugin gets information from you cameras such as:
```
Code=VideoMotion;action=Stop;index=6;data={
"SmartMotionEnable" : true
}
```

Specifically, this plugin looks at the following pieces: `Code=VideoMotion;action=Stop;index=6;`, the code tells us it's a VideoMotion alert, the action is Stop (meaning the alert is over), and the index is the camera #. This is related to the alerts for Smart Person and Vehicle detection. It is the stop response for detecting one of those events. The reason we never see a start request for smart person/vehicle detection is because this plugin does not ask for those "codes". 

I don't have a newer Lorex/Dahua camera system with these features (smart person/vehicle/motion detection), so I can not develop these features. The issue I linked above has a help wanted request for someone with the hardware that supports this software to develop and support those features.

**Comment by Tesla-P100FX** [comment]
So thankful for you sticking with me on this all week😁,  I suspect I should have known that.   But you were right, the last item , I turned off smart motion alerts and boom 🤯 I have alerts!

Saw you are in Texas working on Toyota Auto ,   Is yhat still right?  What do you do exactly


Thanks

Rich

Wear a mask 😷 and be safe

Sent from my Phone 📞, please excuse typos and amusing autocorrects



________________________________

**Comment by kushagharahi** [comment]
Yep no problem! Sorry this plugin doesn't support Smart Motion alerts yet. Eventually someone will hopefully contribute/support the feature or I'll find a need to upgrade to a newer camera.

I recently left Toyota Connected actually. I was doing software for their telematics division, think SOS button, auto-911 in a collision, stolen vehicle locator. Now I'm working on software at Invitae building a bridge between doctor offices and their genetic test ordering system.

I'm going to go ahead and close this issue in favor of #15. If you want to chat some more feel free to reach out @ https://kusha.me/contact !

Of course, please open a new issue if you run into any more issues 🙂
