### ISSUE TITLE
Motion sensor not working

### ISSUE THREAD

**Issue by WummoFTW** [kushagharahi/homebridge-dahua-alerts#2]
Hello, I'm having trouble connecting my Dahua NVR2104 to http notifications, it seems that plugins dont communicate with each other.

**Camera FFmpeg config:
"name": "Camera FFmpeg",
            "localhttp": true,
            "cameras": [
                {
                    "name": "Driveway Camera",
                    "manufacturer": "Dahua",
                    "model": "NVR2104",
                    "serialNumber": "[Redacted]",
                    "firmwareRevision": "V2.4.1",
                    "motion": true,
                    "motionTimeout": 0,
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-i rtsp://[Redacted]:[Redacted]@192.168.0.108:554/cam/realmonitor?channel=1&subtype=0",
                        "maxStreams": 1,
                        "maxWidth": 1184,
                        "maxHeight": 666,
                        "maxFPS": 20,
                        "forceMax": false,
                        "packetSize": 564,
                        "audio": true,
                        "debug": false
                    }**
Dahua Alerts config:
**{
            "cameras": [
                {
                    "index": 1,
                    "cameraName": "Driveway Camera"
                }
            ],
            "host": "192.168.0.108",
            "user": "[Redacted]",
            "pass": "[Redacted]",
            "platform": "dahua-alerts"
        }**

**Comment by kushagharahi** [comment]
What is the issue you’re seeing?

**Comment by WummoFTW** [comment]
The issue is that it doesn't work, the motion sensor icon does show up in the Home app, but it does not detect movement

**Comment by kushagharahi** [comment]
Any logs?

**Comment by WummoFTW** [comment]
**[07/12/2020, 22:37:39] [dahua-alerts] Error Received, reconnecting in 10s 
[07/12/2020, 22:37:49] [dahua-alerts] Error Received, reconnecting in 10s**

**Comment by kushagharahi** [comment]
Can you try setting the index to 0 instead of 1 here:
‘’’
"cameras": [
{
"index": 1,
"cameraName": "Driveway Camera"
}
],
‘’’

**Comment by WummoFTW** [comment]
Ugh, sadly I'm still getting the same error:
**[07/12/2020, 22:58:57] [dahua-alerts] Error Received, reconnecting in 10s**

**Comment by kushagharahi** [comment]
Did you restart homebridge after the config change?

**Comment by WummoFTW** [comment]
Yes, I do

**Comment by xnonim** [comment]
Same problema here, exactly the same message
[dahua-alerts] Error Received, reconnecting in 10s
any idea what im doing wrong?

**Comment by kushagharahi** [comment]
Hey @WummoFTW,


I just pushed up an update to add a bunch of debug logs and some fixes. Could you please install this version (1.0.8) and check if it is working? 

If it doesn't work please enable debug on homebridge and paste the logs here.
You can enable debug logs from the UI on the settings page:
![image](https://user-images.githubusercontent.com/3326002/101971592-22667400-3bf8-11eb-91b8-ce552ab1164e.png)

**Comment by erickkowalski** [comment]
Hi There 

trying to get it working 

im getting this error

[dahua-alerts] Error Received (for more info enable debug logging)
[dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.0.20:443
[dahua-alerts] Reconnecting in 10s.


 {
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "front"
                },
                {
                    "index": 1,
                    "cameraName": "garden"
                }
            ],
            "host": "xxx",
            "user": "xxx",
            "pass": "xxx",
            "homebridgeCameraFfmpegHttpPort": 8088,
            "platform": "dahua-alerts"
        }

i have checked the nvr ip 
username and password are correct as well 

Camera FFmpg plugin works perfectly 

Any Ideas???

Thanks

**Comment by kushagharahi** [comment]
@erickkowalski I'm happy to help however please open a new issue instead of spamming another issue.

**Comment by kushagharahi** [comment]
@WummoFTW since this issue has been open for more than 30 days I am closing it. Please open a new issue if you are still facing issues.
