### ISSUE TITLE
Remote view

### ISSUE THREAD

**Issue by burakcankose** [kushagharahi/homebridge-dahua-alerts#20]
Thanks for the plugin, I have a device outside of my local network, how should I go about transferring it to homekite?  Can cloud connection be made with device sn?

**Comment by kushagharahi** [comment]
This is not a setup help forum. Please use homebridge and this plugin to view your cameras in homekit. Yes cloud connections to the device can be made, just configure the proper ips/ports.

For technical issues such as errors with the plugin please open a new issue describing the problem.
