### ISSUE TITLE
DahuaVTO2MQTT implementation 

### ISSUE THREAD

**Issue by Olepir** [kushagharahi/homebridge-dahua-alerts#23]
Is it possible to implement DahuaVTO2MQTT  into this plugin? Thanks

https://github.com/elad-bar/DahuaVTO2MQTT

**Comment by kushagharahi** [comment]
Unfortunately this feature request is not in the scope of what Homebridge is used for. Homebridge is for exposing IoT device control to Homekit. MQTT message publishing from this plugin, while possible, is out of scope for Homebridge and Homekit, as it does not give any new Homekit control options. 

My suggestion is to run the VTO2MQTT application separately along side this plugin.
