### ISSUE TITLE
DHI-NVR 4208-8P:  Error Details: Didn't get a response from the NVR - connect ECONNREFUSED

### ISSUE THREAD

**Issue by woodgieboodgie** [kushagharahi/homebridge-dahua-alerts#24]
Hi,

I have a Dahua NVR4208-8P and receive the following error when I try to stream from the Dahua eyeball camera (DH-IPC-HDW3641TMP) from HomeKit.  Do I have the channel and sub type correct?

"[Camera FFmpeg] [Camera56] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[06/09/2021, 3:19:28 pm] [Camera FFmpeg] [Camera56] Stream command: /usr/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtsp://auto:passwordremoved@192.168.0.56:554/cam/realmonitor?channel=1&subtype=0 -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -r 30 -f rawvideo -preset ultrafast -tune zerolatency -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -b:v 299k -payload_type 99 -ssrc 1391514 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params FBUjKMt4fWGeloYAUvhqsj0TI0yow/ZfK7XjX1Wh srtp://192.168.0.99:52506?rtcpport=52506&pkt_size=1316 -loglevel level -progress pipe:1
[06/09/2021, 3:19:28 pm] [Camera FFmpeg] [Camera56] FFmpeg exited with code: 1 and signal: null (Error)
[06/09/2021, 3:19:29 pm] [Camera FFmpeg] [Camera56] Stopped video stream."

**Comment by woodgieboodgie** [comment]
.json extract for reference:

 "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Camera FFmpeg",
            "porthttp": 8053,
            "localhttp": true,
            "cameras": [
                {
                    "name": "Camera56",
                    "motion": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://auto:passwordremoved@192.168.0.56:554/cam/realmonitor?channel=1&subtype=0"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "host": "192.168.0.55:8053",
            "user": "auto",
            "pass": "passwordremoved",
            "homebridgeCameraFfmpegHttpPort": 8053,
            "useHttp": true,
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "Camera56"
                }
            ],
            "platform": "dahua-alerts"
        }
    ]
}

**Comment by kushagharahi** [comment]
Hello, all this plugin does is send VideoMotion alerts from dahua camera systems to the plugin [homebridge-camera-ffmpeg](https://github.com/Sunoo/homebridge-camera-ffmpeg). This plugin does _not_ handle snapshots or video. I don't know why the stream or snapshot doesn't work and whether your channel and subtype is correct. I recommend going to the camera-ffmpeg channel in the Homebridge discord for help.

I highly recommend you do not expose your passwords in the future, even for stuff on your local network. 

The following log is expected of this plugin, after 30s of not receiving information from the camera, this plugin will disconnect and reconnect.
> Socket connection timed out or closed by NVR

Feel free to open a new issue if you face a technical issue with this plugin.

**Comment by woodgieboodgie** [comment]
I dont quite follow your suggestion re "channel and subtype".

________________________________

**Comment by kushagharahi** [comment]
Try `channel=1&subtype=1`

**Comment by kushagharahi** [comment]
There are several dahua config suggestions on the `homebridge-camera-ffmpeg` tested config page. You may find that helpful https://sunoo.github.io/homebridge-camera-ffmpeg/configs/

**Comment by woodgieboodgie** [comment]
thank you, got the cameras working.

However, the DVR and alerts are not operational.  Log keeps getting:

[dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.0.55:80
[dahua-alerts] Reconnecting in 10s.

Cant seem to find on the camera where to "Ensure you have enabled https or port 443 on your device if you're getting ECONNREFUSED in the debug logs. Not required by all."

Config extract:

 {
            "name": "Camera FFmpeg",
            "porthttp": 8053,
            "cameras": [
  {
                    "name": "Driveway",
                    "motion": true,
                    "motionTimeout": 0,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i ***@***.***:554/cam/realmonitor?channel=1&subtype=1"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "host": "192.168.0.55",
            "homebridgeCameraFfmpegHttpPort": 8053,
            "user": "admin",
            "pass": "admin",
            "useHttp": true,
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "Driveway"
                }
            ],
            "platform": "dahua-alerts"
        }


________________________________

**Comment by kushagharahi** [comment]
Remove `useHttp: true` from the dahua-alerts config

**Comment by woodgieboodgie** [comment]
Removed 'usehttp: true' and yet to receive alert from camera once movement is detected.

**Comment by kushagharahi** [comment]
Are you getting any errors? Can you post some debug logs?

**Comment by woodgieboodgie** [comment]
Nothing writing to the logs beyond what you have explained is by design.  Could it be the camera (DH-IPC-HDW3641TMP)?  its not on your list.  Connection to the Dahua camera is fine now via FFMpeg.  Below is all that is appearing in the logs:

[07/09/2021, 1:33:01 pm] [dahua-alerts] Socket connection timed out or closed by NVR.
[07/09/2021, 1:33:01 pm] [dahua-alerts] Reconnecting in 1s.
[07/09/2021, 1:33:32 pm] [dahua-alerts] Socket connection timed out or closed by NVR.
[07/09/2021, 1:33:32 pm] [dahua-alerts] Reconnecting in 1s.

**Comment by woodgieboodgie** [comment]
Just confirming that the plugin picks up movement when the Dahua camera is set to notify user within Homekit?

![thumbnail_IMG_3866](https://user-images.githubusercontent.com/52473319/132281389-5568f9cd-d111-4c4e-9431-7f9a8db591de.jpg)

**Comment by kushagharahi** [comment]
Can you trigger a motion alert and post any subsequent debug logs? 

> Could it be the camera (DH-IPC-HDW3641TMP)? its not on your list.

No that list is just cameras models I've collected from issues like this one. It is my no means a comprehensive list

> Just confirming that the plugin picks up movement when the Dahua camera is set to notify user within Homekit?

yes

**Comment by woodgieboodgie** [comment]
Unfortunately motion does not trigger an alert and confirming that 'motion detection' checkbox is flagged on the "Alarms" tab of the camera itself.
![motion](https://user-images.githubusercontent.com/52473319/132283079-e8f493fa-4705-49c4-90aa-dbe2850de4ea.PNG)

**Comment by kushagharahi** [comment]
Are there any other debug logs besides the socket connection timing out, especially when you trigger a motion alert?

**Comment by woodgieboodgie** [comment]
No logs for motion when Homekit is off and movement is made infront of the camera.

**Comment by woodgieboodgie** [comment]
Other cams highlight movement in a green box around the subject.  is that what we are looking for here?

**Comment by kushagharahi** [comment]
So there are no other debug logs at all for dahua-alerts besides the following? I really can not debug your system without logs. Doesn’t have to be motion related, any logs will do as long as it says “dahua-alerts” 

[07/09/2021, 1:33:01 pm] [dahua-alerts] Socket connection timed out or closed by NVR.
[07/09/2021, 1:33:01 pm] [dahua-alerts] Reconnecting in 1s.
[07/09/2021, 1:33:32 pm] [dahua-alerts] Socket connection timed out or closed by NVR.
[07/09/2021, 1:33:32 pm] [dahua-alerts] Reconnecting in 1s.

the green boxes represent smart motion, this plugin only supports VideoMotion. On my system there a green letter C from that turns into a red letter M on the left hand corner next to “CAM #”

**Comment by kushagharahi** [comment]
Smart motion generally overrides VideoMotion FYI. It’s one or the other.

**Comment by woodgieboodgie** [comment]
i believe i have set the camera properly to trigger upon movement detection unless there is a setting that i have missed?

![Capture](https://user-images.githubusercontent.com/52473319/132287967-f8a064e4-01f5-4a13-8ee4-9927afbc1fbc.PNG)

**Comment by kushagharahi** [comment]
﻿Can you try turning off smart motion detection?

I assume that means there are no other logs whatsoever?

**Comment by woodgieboodgie** [comment]
Smart Motion detection disabled.  Video 'motion detection' still enabled.  No additional entries from dahua-alerts in logs.

![Capture](https://user-images.githubusercontent.com/52473319/132289990-86a52324-d2d0-4d1b-8e61-99e26c91b5ac.PNG)

**Comment by woodgieboodgie** [comment]
fyi, camera is not connected via DVR.  It has been removed from the PoE port at the back of the DVR and given 192.168.0.136 address on the private LAN via PoE port on dedicated switch.  Passwords have been set the same on DVR and camera (without any special characters, just alpha numeric).

**Comment by kushagharahi** [comment]
Is the plugin pointing to the DVR or camera? Can you point the plugin to your camera instead of the DVR?

**Comment by woodgieboodgie** [comment]
THAT'S IT.  Thank you!  (Silly mistake by me, alert has now appeared as Dahua plugin points to the camera itself).  

That removes the DVR from the setup though.  How will I handle several cameras?

**Comment by kushagharahi** [comment]
Alright! Glad it was an easy fix!

This plugin supports as many cameras as you got and they can be on completely different hosts

**Comment by kushagharahi** [comment]
Here’s the documentation: https://github.com/kushagharahi/homebridge-dahua-alerts#override-camera-connection-credentials

Going to close this issue now, let me know if you run into any other trouble with the plugin!

**Comment by woodgieboodgie** [comment]
close it but just to clarify when the DVR and cameras are on the network, the dahua alerts config points to the DVR and the override config provides the username and password for each individual camera?

________________________________

**Comment by kushagharahi** [comment]
Yeah but include `host` as well. You can also just define every cameras credential per camera something like

```
    "cameras": [
        {
            "index": 0,
            "cameraName": "Driveway"
            "cameraCredentials": {
                    "host": "XX.XX.XX.XX",
                    "user": "admin",
                    "pass": "XX"
            },         {
            "index": 0,
            "cameraName": "Porch"
            "cameraCredentials": {
                    "host": "XX.XX.XX.XX",
                    "user": "admin",
                    "pass": "XX"
            }
        },
```

The plugin will de-duplicate hosts. The way you described is best if you have one DVR/NVR and some standalone cameras, but does not work if you have two+ DVRs. Hopefully that makes sense.

**Comment by woodgieboodgie** [comment]
Excellent and thanks so much for your help.

Out of curiosity which country are you in? I am in Australia.

On 7 Sep 2021, at 4:33 pm, Kusha Gharahi ***@***.***> wrote:

﻿

Yeah but include host as well. You can also just define every cameras credential per camera something like

    "cameras": [
        {
            "index": 0,
            "cameraName": "Driveway"
            "cameraCredentials": {
                    "host": "XX.XX.XX.XX",
                    "user": "admin",
                    "pass": "XX"
            },         {
            "index": 0,
            "cameraName": "Porch"
            "cameraCredentials": {
                    "host": "XX.XX.XX.XX",
                    "user": "admin",
                    "pass": "XX"
            }
        },


The plugin will de-duplicate hosts. The way you described is best if you have one DVR/NVR and some standalone cameras, but does not work if you have two+ DVRs. Hopefully that makes sense.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkushagharahi%2Fhomebridge-dahua-alerts%2Fissues%2F24%23issuecomment-914030624&data=04%7C01%7C%7C9848c1874d514a03357c08d971c9635c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637665932035322940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4iYlhHEvyz%2BlK6WeIheys4i4Nq3iwB09KvQpjkEF%2Bqo%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMQK3Z5ZBKXD2ULXV3HWNYDUAWW3DANCNFSM5DPVSYJA&data=04%7C01%7C%7C9848c1874d514a03357c08d971c9635c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637665932035332895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5Cuc9ar6uMgCBGwQYbkQTKpvNdmIJ7ShG3K1mJa23tg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9848c1874d514a03357c08d971c9635c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637665932035342852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hQn33EFrch00xBqgMB%2F6C2YzytQjzLK%2FjyUXqsgWD4k%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9848c1874d514a03357c08d971c9635c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637665932035342852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oIuUOAoJL2wNySliuyrZDCQa28eF%2FnPT8bguS9gT2F0%3D&reserved=0>.

**Comment by kushagharahi** [comment]
That’s dope that you’re located In Australia! I am located in the US, Texas specifically.

**Comment by woodgieboodgie** [comment]
tell me about it.  approaching 300 days of lockdown due to elected officials thinking they can drive covid to zero. plus they stuffed up the rollout.

did you have any lockdowns?  press we received suggested it had been let to run wild in Texas..

________________________________

**Comment by kushagharahi** [comment]
No real lockdowns here. Most stuff that shutdown was fairly voluntary and schools had an option of attending virtually. Now everything is operating as if it’s normal and people with non covid, curable problems that need a hospital are dying because the hospitals are full of people with covid. Run wild is an understatement honestly. 

Right now there are court battles whether schools and cities can issue mask mandates. 

Also it’s so politicized that I probably shouldn’t even be talking about it here. 


With your lockdowns how is the # of cases and hospital situation? Right now we are almost nearly to the peak of cases again

**Comment by woodgieboodgie** [comment]
Sydney has about 1400 daily cases but they were so slow to lock down anything the delta variant is now taking hold. Elective surgery cancelled.

Melbourne is at ~200 daily cases and suffering through the toughest lockdowns globally. Number 6 at the moment. Can’t leave home after 9pm and can only go out for 1hr exercise or food an must stay within 5km from home. Hospitals are open, elective surgery open.

What you have said is probably a crystal ball for us as the population vaccinates very slowly and pressure to open up mounts.

So do you know many that have got covid?

On 7 Sep 2021, at 5:03 pm, Kusha Gharahi ***@***.***> wrote:

﻿

No real lockdowns here. Most stuff that shutdown was fairly voluntary and schools had an option of attending virtually. Now everything is operating as if it’s normal and people with non covid, curable problems that need a hospital are dying because the hospitals are full of people with covid. Run wild is an understatement honestly.

Right now there are court battles whether schools and cities can issue mask mandates.

Also it’s so politicized that I probably shouldn’t even be talking about it here.

With your lockdowns how is the # of cases and hospital situation? Right now we are almost nearly to the peak of cases again

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkushagharahi%2Fhomebridge-dahua-alerts%2Fissues%2F24%23issuecomment-914045582&data=04%7C01%7C%7Cc6f13b43d08740291dc508d971cd8f1b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637665949970420881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AYGz9yD3hyKigK3sn8C%2BwSQ%2FJUE%2FMEFSP4FJj1fqtuY%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMQK3Z4IPRHLUXGDKT5QUGDUAW2LBANCNFSM5DPVSYJA&data=04%7C01%7C%7Cc6f13b43d08740291dc508d971cd8f1b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637665949970430830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lggrzYxbukt7%2B8xG85J%2FGeYAPnEMXlNKnMse9JciQB8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc6f13b43d08740291dc508d971cd8f1b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637665949970430830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IwnGM7qWVzQAm3tkPreNYJ%2BjartB8eV9OhpdZYo3R4k%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc6f13b43d08740291dc508d971cd8f1b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637665949970440794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0tJ7QHD5cNDnpZZxHosAGVKFcSD9am8707HE9hGAglI%3D&reserved=0>.
