### ISSUE TITLE
LNK7108A - "Error Details: Status Code: 404 Response: Not Found on Host:" - That is the correct ip listed, and debug logs are on.

### ISSUE THREAD

**Issue by kushagharahi** [kushagharahi/homebridge-dahua-alerts#25]
I appear to be getting a 404 error. That is the correct ip listed, and debug logs are on.

# Output from both dist and release 
```json5
[05/09/2021, 20:09:52] [dahua-alerts] Error Details: Status Code: 404 Response: Not Found on Host: 192.168.4.21
[05/09/2021, 20:09:52] [dahua-alerts] Reconnecting in 10s.
[05/09/2021, 20:09:52] [dahua-alerts] Error received from host: 192.168.4.21 (for more info enable debug logging
```

_Originally posted by @iRayanKhan in https://github.com/kushagharahi/homebridge-dahua-alerts/issues/21#issuecomment-913270385_

**Comment by kushagharahi** [comment]
Hi @iRayanKhan let's work on your issue in this thread.

The other issue is unrelated to your issue. What camera system do you have? You mentioned you have 4 cameras and an NVR. Are they all connected to the NVR? Could you post your config (minus passwords)

**Comment by iRayanKhan** [comment]
Hey @kushagharahi thanks for looking at my issue,

this is my ```Device Type:``` "LNK7108A". All 4 Cameras are connected to a Lorex Flir NVR system. 


# Dahua Config:
```json5
{
            "host": "192.168.4.21",
            "user": "",
            "pass": "",
            "homebridgeCameraFfmpegHttpPort": 8080,
            "useHttp": true,
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "Driveway"
                },
                {
                    "index": 1,
                    "cameraName": "Front Foor Camera"
                },
                {
                    "index": 2,
                    "cameraName": "Backyard Camera"
                },
                {
                    "index": 3,
                    "cameraName": "Side Yard"
                }
            ],
            "platform": "dahua-alerts"
        }
```

# FFmpeg Config:

```Json5

            "name": "Camera FFmpeg",
            "porthttp": 8080,
            "localhttp": true,
            "cameras": [
                {
                    "name": "Driveway",
                    "motion": true,
                    "switches": false,
                    "motionTimeout": 0,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://creds@192.168.4.21:554/ch01/1",
                        "vcodec": "h264_omx"
                    }
                },
                {
                    "name": "Front Door Camera",
                    "motion": true,
                    "doorbell": false,
                    "switches": false,
                    "motionTimeout": 0,
                    "motionDoorbell": false,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://creds@192.168.4.21:554/ch02/1",
                        "vcodec": "h264_omx"
                    }
                },
                {
                    "name": "Backyard Camera",
                    "motion": true,
                    "motionTimeout": 0,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://creds@192.168.4.21:554/ch04/1",
                        "vcodec": "h264_omx"
                    }
                },
                {
                    "name": "Side Yard",
                    "motion": true,
                    "motionTimeout": 0,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://creds@192.168.4.21:554/ch03/1",
                        "vcodec": "h264_omx"
                    }
                }
            ],
            "_bridge": {
                "username": "",
                "port": 55142
            },
            "platform": "Camera-ffmpeg"
        }
```

The NVR utilizes Http port 80, does that make a difference?

**Comment by kushagharahi** [comment]
Can you try setting the option `useHttp` to true?

**Comment by kushagharahi** [comment]
Well since it uses port 80, your setting `"useHttp": true` should be the fix, but just to test, could you make this option false?

**Comment by iRayanKhan** [comment]
Setting it to false returns this:

I have port 443 open, the rtsp port is 554. 

```json5
[06/09/2021, 23:38:15] [dahua-alerts] Error Received (for more info enable debug logging)
[06/09/2021, 23:38:15] [dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.4.21:443
[06/09/2021, 23:38:16] [dahua-alerts] Reconnecting in 10s.
```

**Comment by kushagharahi** [comment]
The rtsp port is different than the api port. Also you don’t have to open ports on your router for local network connections and highly recommend you don’t do that, doing so opens the port to the outside world. 

It looks like Lorez Flir NVR is not a rebrand of Dahua but rather

**Comment by kushagharahi** [comment]
The rtsp port is different than the api port. Also you don’t have to open ports on your router for local network connections and highly recommend you don’t do that, doing so opens the port to the outside world. 

It looks your camera system does not have any ONVIF apis (ONVIF is the open standard for camera systems) but lower firmware versions might per this thread: https://ipcamtalk.com/threads/lorex-software-flir-client-12-weird-issue.30018/page-2#post-360509

Unfortunately that means that your NVR system is incompatible with this plugin. Your rtsp connection strings are completely different than all dahua camera systems I’ve seen as well. It looks like that NVR has non standard software, sorry

**Comment by iRayanKhan** [comment]
Thanks for helping me try!

Looks like these won't be getting HKSV lol.

**Comment by kushagharahi** [comment]
Sorry :( I think HKSV through camera-ffmpeg is quite a bit away if at all possible though if that makes it any better

**Comment by iRayanKhan** [comment]
> Sorry :( I think HKSV through camera-ffmpeg is quite a bit away if at all possible though if that makes it any better


There is an active PR in hap-nodejs which gives some hope

**Comment by iRayanKhan** [comment]
Hey @kushagharahi I did some digging, and found I can enable ONVIF on two out of the four cameras. I still get the same error though. 

The cameras share the same IP, so I can't add them as a separate device. 

Any thoughts?

**Comment by kushagharahi** [comment]
I think what you have to do is use a PoE switch to give all your cameras separate ip addresses so you can set up credentials per camera
![335F74FB-00C2-41F9-8BFE-FE19895F7ABE](https://user-images.githubusercontent.com/3326002/132958184-16aea1dc-c06e-42ea-97b8-2419257fa7c2.png)

**Comment by kushagharahi** [comment]
Person in #24 has a PoE setup and was able to accomplish what you’re looking for if you want to take a look

**Comment by kushagharahi** [comment]
Here's the manual btw: https://www.lorextechnology.com/downloads/security-camera-system/LNK716394B/LNK7000_SERIES_MANUAL_EN_R1_web.pdf

Looks like you just have to keep the cameras on the same network and it can auto detect them so you won't lose NVR functionality. Kinda neat

**Comment by iRayanKhan** [comment]
Thanks for the suggestion. 

I have a PoE switch now, but using the ONVIF protocol doesn't allow me to record or edit any camera settings, unless I change the protocol to private. 

Going to see if this plugin works later tomorrow, and will report back.

**Comment by iRayanKhan** [comment]
Hey @kushagharahi,

My cameras aren't ONVIF compliant, even though it has ONVIF support. 

I have switched to Scrypted, and utilize OpenCV for motion detection, and how have HKSV. Thank you for all the help!
