### ISSUE TITLE
Please add support for camera-only IMOU Ranger IPC-A22EP

### ISSUE THREAD

**Issue by ahmadnazirafiq** [kushagharahi/homebridge-dahua-alerts#26]
Hi,

I have an IMOU Ranger 2 camera with the source URL -i rtsp://admin:XXXXXXXX@192.168.1.XXX:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif and it works in HomeKit just fine. But I haven't been able to expose its motion sensor to camera-ffmpeg using dahua plugin. Any ideas?

**Comment by kushagharahi** [comment]
Can you post the debug logs for dahua-alerts?

**Comment by ahmadnazirafiq** [comment]
Hi, sorry for late response. Here’s what I’m seeing:

![B3FD97D8-CF18-42B5-92C9-903AEE8EDA29](https://user-images.githubusercontent.com/66505845/137365868-dd7f30da-8656-4b0f-847d-a249d040197d.jpeg)

It’s a standalone camera and not using NVR. Not sure what’s wrong.

**Comment by kushagharahi** [comment]
Can you post your config with your passwords removed?

**Comment by kushagharahi** [comment]
Closing due to lack of response. Please open a new issue if you would like to debug further.
