### ISSUE TITLE
any way to debug?

### ISSUE THREAD

**Issue by xnonim** [kushagharahi/homebridge-dahua-alerts#3]
Hi, first of all, thanks for this very usefull plugin,
first days using it was working like a charm, very stupid from me i update the dvr and now it´s getting this error

[12/11/2020, 9:47:36 AM] [dahua-alerts] Error Received, reconnecting in 10s 
[12/11/2020, 9:47:46 AM] [dahua-alerts] Error Received, reconnecting in 10s 
[12/11/2020, 9:47:56 AM] [dahua-alerts] Error Received, reconnecting in 10s 

i´ve tried many things, (as far as my knowdledge allow me since i´m very noob in all this), 

i already checked the api is still wortking (using this link (https://192.168.x.x/cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect))
and it responds me with a lot of information, so im assuming it is still working using the same api, 
maybe you can guide me where is maybe my problem

ps: sorry if something is badwritten, english is not my native language

**Comment by xnonim** [comment]
I dont know if it has something to do, but since I update the dvr (as far i remember), now force me to enter by https,
i've tried modifying the dahua,js adding: 
	    rejectUnauthorized: false,
but it doesn´t work for me

if I downgrade my dvr, will maybe fix all this problem??

**Comment by kushagharahi** [comment]
Hey @xnonim,

I'm really happy to hear this worked for you before! Not to worry we will figure out the issue.

I just pushed up an update to add a bunch of debug logs. Could you please install this version (1.0.6), enable debug on homebridge and paste the logs here?

You can enable debug logs from the UI on the settings page:
![image](https://user-images.githubusercontent.com/3326002/101971592-22667400-3bf8-11eb-91b8-ce552ab1164e.png)

By the way, please keep your comments contained to this issue.

**Comment by xnonim** [comment]
Hi!!! thanks for the quick answer, i´ve been all the day trying to fix it myself.
i did the same exercise using postman that you told another guy 

here are the logs you asked 

[12/12/2020, 1:03:27 AM] [dahua-alerts] Error Received (for more info enable debug logging)
[12/12/2020, 1:03:27 AM] [dahua-alerts] Error Details: Status Code: 401 Response: Unauthorized
[12/12/2020, 1:03:27 AM] [dahua-alerts] Reconnecting in 10s

ps: sorry, first time using all this

**Comment by kushagharahi** [comment]
No worries! 

Your username and or password looks to be incorrect, double check them

**Comment by xnonim** [comment]
yes, i check them, are correct.

i dont know if it helps in something, but using postman if i make a basic auth, it says Unauthorized(1st pic) , but if i changed to a digest auth, it work perfect(2nd pic)

![401](https://user-images.githubusercontent.com/61104752/101973531-89dfec00-3c17-11eb-8f3a-01229df42282.PNG)
![200](https://user-images.githubusercontent.com/61104752/101973528-88aebf00-3c17-11eb-9c26-aab56b77594c.PNG)

**Comment by kushagharahi** [comment]
So I don't use basic auth.

If you GET `user:pass@192.168.1.100/cgi-bin/eventManager.cgi?action=attach&codes=[VideoMotion]` without an auth selected in the `Authorization` tab, what happens?

Like so:
![image](https://user-images.githubusercontent.com/3326002/101975197-5a71b500-3c00-11eb-9f1d-e86ca664943b.png)

**Comment by xnonim** [comment]
same, unauthorized.
![unu](https://user-images.githubusercontent.com/61104752/101975280-ffe55280-3c19-11eb-9fa7-84c6c0ada4dd.PNG)

**Comment by kushagharahi** [comment]
Ok, try this, replace the `dist` folder contents in `homebridge\node_modules\homebridge-dahua-alerts\dist` with the contents of this zip. Then restart homebridge. I made an attempt at digest auth but I'm not sure if it will work.

[dist.zip](https://github.com/kushagharahi/homebridge-dahua-alerts/files/5682504/dist.zip)

**Comment by xnonim** [comment]
ok, now appear this

(node:1957) UnhandledPromiseRejectionWarning: TypeError: this.HEADERS.add is not a function
    at /homebridge/node_modules/homebridge-dahua-alerts/src/dahua.ts:93:38
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kushagharahi** [comment]
Ok try this
[dist.zip](https://github.com/kushagharahi/homebridge-dahua-alerts/files/5682513/dist.zip)

**Comment by xnonim** [comment]
ok, now it says this:

[12/12/2020, 2:13:49 AM] [39m[31mTypeError: Cannot read property 'substr' of undefined[39m
[31m    at DahuaEvents.parseEventData (/homebridge/node_modules/homebridge-dahua-alerts/src/dahua.ts:149:31)[39m
[31m    at Socket.<anonymous> (/homebridge/node_modules/homebridge-dahua-alerts/src/dahua.ts:55:34)[39m
[31m    at Socket.emit (events.js:327:22)[39m
[31m    at addChunk (_stream_readable.js:309:12)[39m
[31m    at readableAddChunk (_stream_readable.js:284:9)[39m
[31m    at Socket.Readable.push (_stream_readable.js:223:10)[39m
[31m    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)[39m
[37m[12/12/2020, 2:13:49 AM] [39mGot SIGTERM, shutting down Homebridge...

but it sometimes appear like it turn on and off the switches, but for some reason, when it does, broke entire homebridge

**Comment by kushagharahi** [comment]
There should be a debug log before this that starts with `Response recieved:`, can you post that?

**Comment by xnonim** [comment]
this is what i could find ( im deleting the others plugin to make it easy to find)

[37m[12/12/2020, 2:27:43 AM] [39m[36m[dahua-alerts] [39m[31mError Received (for more info enable debug logging)[39m
[37m[12/12/2020, 2:27:43 AM] [39m[36m[dahua-alerts] [39m[90mError Details: Status Code: 401 Response: Unauthorized[39m
[37m[12/12/2020, 2:27:43 AM] [39m[36m[dahua-alerts] [39m[90mReconnecting in 10s.[39m

ps: sensors on my iphone turn on, then off, and the homebridge restart again

**Comment by xnonim** [comment]
ok im getting this, but the, it says "ok"
[37m[12/12/2020, 2:29:48 AM] [39m[36m[dahua-alerts] [39m[31mError Received (for more info enable debug logging)[39m
[37m[12/12/2020, 2:29:48 AM] [39m[36m[dahua-alerts] [39m[90mError Details: Status Code: 401 Response: Unauthorized[39m
[37m[12/12/2020, 2:29:48 AM] [39m[36m[dahua-alerts] [39m[90mReconnecting in 10s.



[37m[12/12/2020, 2:29:48 AM] [39m[36m[dahua-alerts] [39m[90mResponse recieved: HTTP/1.1 200 OK[39m
[90mCache-Control: no-cache[39m
[90mPragma: no-cache[39m
[90mExpires: Thu, 01 Dec 2099 16:00:00 GMT[39m
[90mConnection: Keep-Alive[39m
[90mContent-Type: multipart/x-mixed-replace; boundary=myboundary[39m
[90m[39m
[90m[39m
[37m[12/12/2020, 2:29:48 AM] [39m[31mTypeError: Cannot read property 'substr' of undefined[39m
[31m    at DahuaEvents.parseEventData (/homebridge/node_modules/homebridge-dahua-alerts/src/dahua.ts:149:31)[39m
[31m    at Socket.<anonymous> (/homebridge/node_modules/homebridge-dahua-alerts/src/dahua.ts:55:34)[39m
[31m    at Socket.emit (events.js:327:22)[39m
[31m    at addChunk (_stream_readable.js:309:12)[39m
[31m    at readableAddChunk (_stream_readable.js:284:9)[39m
[31m    at Socket.Readable.push (_stream_readable.js:223:10)[39m
[31m    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)[39m

**Comment by kushagharahi** [comment]
Ok this should stop the crashing but it's still not going to work I think. 
[dist.zip](https://github.com/kushagharahi/homebridge-dahua-alerts/files/5682540/dist.zip)

Send more logs if (when) it doesn't work

**Comment by xnonim** [comment]
yes, it stop crashing homebridge, heres the logs

[12/12/2020, 2:45:04 AM] [dahua-alerts] Could not parse event data! (for more info enable debug logging)
[12/12/2020, 2:45:04 AM] [dahua-alerts] Event data received: HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Expires: Thu, 01 Dec 2099 16:00:00 GMT
Connection: Keep-Alive
Content-Type: multipart/x-mixed-replace; boundary=myboundary


[12/12/2020, 2:45:34 AM] [dahua-alerts] Socket connection timed out or closed by NVR.
[12/12/2020, 2:45:34 AM] [dahua-alerts] Reconnecting in 1s.
[12/12/2020, 2:45:35 AM] [dahua-alerts] Response recieved: HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Expires: Thu, 01 Dec 2099 16:00:00 GMT
Connection: Keep-Alive
Content-Type: multipart/x-mixed-replace; boundary=myboundary


[12/12/2020, 2:45:35 AM] [dahua-alerts] Could not parse event data! (for more info enable debug logging)
[12/12/2020, 2:45:35 AM] [dahua-alerts] Event data received: HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Expires: Thu, 01 Dec 2099 16:00:00 GMT
Connection: Keep-Alive
Content-Type: multipart/x-mixed-replace; boundary=myboundary

**Comment by kushagharahi** [comment]
So your response looks different so I'm just trying to see what the difference is. Can you try this?

[dist.zip](https://github.com/kushagharahi/homebridge-dahua-alerts/files/5682549/dist.zip)

**Comment by kushagharahi** [comment]
Is it working at all right now? If you trigger the motion alarms

**Comment by xnonim** [comment]
well, actually its working!!, the error that appear in logs, but the sensors are working correctly

**Comment by xnonim** [comment]
omg!! yeah they´re are working!! you dont know how much i appreciate all this, do you have some ways to donate or something like that??? maybe a patreon??

**Comment by kushagharahi** [comment]
Ok awesome glad to hear it! 

I don't have anyway to accept donations yet (I appreciate it though) but it would be a big help for me if you can test the new version I'm about to publish to make sure it works. Would you be able to do that?

**Comment by xnonim** [comment]
yes of course!! whatever you need, I hope to be of help

**Comment by kushagharahi** [comment]
Ok I just published 1.0.7. If you could update, check if it's still working for you and those errors aren't appearing anymore that would be really fantastic! 

Also what is your DVR model # so I can add it to the README that it is confirmed working?

**Comment by xnonim** [comment]
i was about to write you an error, but was my settings of motions on dvr bad. everything works awesome.
the model od my dvr is  DHI-HCVR4116HS-S3, sorry the delay, i was testing everything´´s ok

**Comment by kushagharahi** [comment]
Hurray. Good work on the debugging. We would not have been able to do this out without the digest auth stuff you figured out.

Going to close this issue, feel free to open a new one if you run into any other issues!

**Comment by xnonim** [comment]
thanks again, and whatever you need, i owe you one!!
