### ISSUE TITLE
Lorex 2K Doorbell B451AJD-E

### ISSUE THREAD

**Issue by b-slick** [kushagharahi/homebridge-dahua-alerts#30]
Hi,

I got this doorbell showing on homebridge-camera-ffmpeg, but when trying to get motions to work I get the following:

[dahua-alerts] Error received from host: 192.168.1.10 (for more info enable debug logging)
[dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.1.10:80
[dahua-alerts] Reconnecting to 192.168.1.10 in 10s.

I turned on use http in the plugin and I still get the same message for https as you can see the ports are different.

[dahua-alerts] Error received from host: 192.168.1.10 (for more info enable debug logging)
[dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.1.10:443
[dahua-alerts] Reconnecting to 192.168.1.10 in 10s.

I don’t see anywhere on the app that shows that I can turn on https or anything within the Lorex Home App. The camera is standalone, so no NVR needed.

Has anyone got this to work?

Thanks!

**Comment by kushagharahi** [comment]
I suspect the doorbell is not ONVIF compliant and uses a different API than the regular camera systems.

Could you post your config, both FFMPEG and dahua-alerts in here? Please remove any passwords.

**Comment by b-slick** [comment]
Hi, please see below, I’ve replaced with usr and pwd instead. To clarify the .108 is the NVR that works with the stream and motion, so wanted to add the doorbell which is .10 a standalone. Thanks.

{
            "name": "Camera FFmpeg",
            "porthttp": 8088,
            "localhttp": true,
            "cameras": [
                {
                    "name": "Front Yard",
                    "motion": true,
                    "switches": false,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://usr:pwd@192.168.1.108:554/cam/realmonitor?channel=1&subtype=1",
                        "stillImageSource": "-i http://usr:pwd@192.168.1.108/cgi-bin/snapshot.cgi?loginuse=usr&loginpas=pwd",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 15,
                        "vcodec": "copy"
                    }
                },
                {
                    "name": "Doorbell",
                    "motion": true,
                    "doorbell": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-i rtsp://usr:pwd@192.168.1.10:554/cam/realmonitor?channel=1&subtype=1",
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "audio": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },


{
            "host": "192.168.1.108",
            "user": "usr",
            "pass": "pwd",
            "homebridgeCameraFfmpegHttpPort": 8088,
            "useHttp": true,
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "Front Yard"
                },
                {
                    "index": 0,
                    "cameraName": "Doorbell",
                    "cameraCredentials": {
                        "host": "192.168.1.10",
                        "user": "usr",
                        "pass": "pwd",
                        "useHttp": false
                    }
                }
            ],
            "platform": "dahua-alerts"
        },

**Comment by b-slick** [comment]
If it’s not ONVIF compliant, does that mean this plugin doesn’t support it? Is there another way to get motions working then? Thanks.

**Comment by kushagharahi** [comment]
Can you try connecting to it with SmartPSS software or similar to see if there are any video motion settings?

From https://ipcamtalk.com/threads/looking-for-a-video-doorbell-that-complies-with-this-list.54374/page-2#post-551647
> I accessed it with the SmartPSS desktop application using port 35000. I have used port 37777 with Amcrest and Dahua. Many settings not available in the Lorex Home app were there. I also used iDMSS Plus and DMSS on my phone to access the doorbell. The B451AJD-E became flaky, though, about talking from my phone through its speaker with iDMSS Plus and DMSS. I could not add the B451AJD-E to Amcrest ViewPro using port 35000.

Another possibility is that the VideoMotion api could be located on one of the other ports. Maybe one of the ones listed in that post? 

I can’t find any documentation about this doorbell camera having apis or being ONVIF compliant. Contacting Lorex directly might have some answers too

**Comment by b-slick** [comment]
Yeah, SmartPSS connects to it via port 35000. I had used it before to help figure out RTSP url as it was using channel 1 instead of 0. Based on the app there is a video detect option that shows Motion Detect or Camera Masking settings. Basically, it’s the channel number, arm/disarm period, anti-dither, zone, record channel, snapshot, etc. I see at the bottom options to upload to cloud, show msg, send email, buzzer, alarm upload and message checkboxes.

Under Network they have a connect option that shows the following for the device:
Max connect: 128
TCP Port: 35000
UDP Port: 35001
Http Port: 80
RTSP Port: 554
HTPS Port: n/a (can’t edit this or add)

Seems like I can edit these ports as well, not sure if this updates it back to the device.

If it is using 35000, what do I need to do for the plugin to look at that port?

Thanks.

**Comment by b-slick** [comment]
Lorex said it wasn’t ONVIF but WIFI. Is there a way to look at other ports or need to do with SmartPSS? Thanks

**Comment by kushagharahi** [comment]
Unfortunately this doorbell won't be supported as the method of communication this plugin uses is ONVIF and the doorbell does not support that.
