### ISSUE TITLE
Lorex/Dahua alerts over Apple HomeKit

### ISSUE THREAD

**Issue by riiveraluis** [kushagharahi/homebridge-dahua-alerts#34]
The solution about how to add Smart motion alerts seems to be already resolved by the user IGx89. Why is not added already so the comunity can test it? https://ipcamtalk.com/threads/dahua-smd-alerts-over-apple-homekit.55579/

Original feature request https://github.com/kushagharahi/homebridge-dahua-alerts/issues/15#issue-845615035

**Comment by kushagharahi** [comment]
That is a feature request. It needs to be implemented and tested. After it is tested and merged, people will have problems with it. Someone will have to support and debug those problems. I do not have the hardware to debug and support those features and no one has stepped up offering to make the change and support it.

This is not an issue that needs resolving and there is an open feature request already. The comments were closed to prevent snippy comments like this.

**Comment by riiveraluis** [comment]
I have the hardware. I was willing to test it. Very curious now since the camera ffmpeg plugin will soon have HKSV support and I was using your plugin to receive motion alerts but even shadows triggered motions sometimes. Smart detection is a must. Thanks for your work I hope this gets sorted out someday.

**Comment by kushagharahi** [comment]
Sorry but testing it is not enough -- take a look at some of the closed support requests. The problems people have are pretty complex. Without someone always on deck or the relevant hardware to help debug these issues I'm afraid I can not support this feature.
