### ISSUE TITLE
Not getting a response from the NVR

### ISSUE THREAD

**Issue by woodgieboodgie** [kushagharahi/homebridge-dahua-alerts#39]
Hi,

Is there a setting on the camera that specifies port 443?  
My cameras are working but no motion detection despite setting 'motion detection' to ON, and 'SmartMotion' set to OFF.  
NVR address 10.0.1.192, camera address 10.0.1.185.
Also, is port 8053 specified in config but is there a corresponding setting for that on camera or NVR?

{
    "platform": "dahua-alerts",
    "host": "10.0.1.192",
    "homebridgeCameraFfmpegHttpPort": 8053,
    "user": "nvrtestuser",
    "pass": "password",
    "cameras": [
        {
            "index": 0,
            "cameraName": "Camera1",
            "cameraCredentials": {
                "host": "10.0.1.185",
                "user": "cameratestuser",
                "pass": "password""
            }
        }
    ]
}

**Comment by woodgieboodgie** [comment]
Are you out there Kushagharahi? Would really appreciate help to close this issue out.

**Comment by kushagharahi** [comment]
@woodgieboodgie Sorry about that, are your cameras connected to your NVR?

**Comment by woodgieboodgie** [comment]
And cams are connected to network switch not the NVR

On 5 Oct 2022, at 2:26 pm, Kusha Gharahi ***@***.***> wrote:

﻿

@woodgieboodgie<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwoodgieboodgie&data=05%7C01%7C%7Cc91a688deb574e936b1a08daa681542e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638005371654390427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MgIr9wXo6objKRPZlx3m6ja5UDITK%2FSgUArGhwTh8qo%3D&reserved=0> Sorry about that, are your cameras connected to your NVR?

**Comment by kushagharahi** [comment]
The NVR does not need to be specified in the config then, just individual cameras.

Can you post your ffmpeg config here?

**Comment by woodgieboodgie** [comment]
CAMERA-FFMPEG


{
    "name": "Camera FFmpeg",
    "porthttp": 8088,
    "localhttp": true,
    "cameras": [
        {
            "name": "Camera1",
            "motion": true,
            "motionTimeout": 0,
            "unbridge": true,
            "videoConfig": {
                "source": "-i ***@***.***:554/cam/realmonitor?channel=1&subtype=1"
            }
        },
        {
            "name": "Camera2",
            "motion": true,
            "motionTimeout": 0,
            "unbridge": true,
            "videoConfig": {
                "source": "-i ***@***.***:554/cam/realmonitor?channel=1&subtype=1"
            }
        },
        {
            "name": "Camera3",
            "motion": true,
            "motionTimeout": 0,
            "unbridge": true,
            "videoConfig": {
                "source": "-i rtsp:// user:pass @10.0.1.187:554/cam/realmonitor?channel=1&subtype=1"
            }
        },
        {
            "name": "Camera4",
            "motion": true,
            "motionTimeout": 0,
            "unbridge": true,
            "videoConfig": {
                "source": "-i rtsp:// user:pass @10.0.1.188:554/cam/realmonitor?channel=1&subtype=1"
            }
        },
        {
            "name": "Camera5",
            "motion": true,
            "motionTimeout": 0,
            "unbridge": true,
            "videoConfig": {
                "source": "-i rtsp:// user:pass @10.0.1.189:554/cam/realmonitor?channel=1&subtype=1"
            }
        },
        {
            "name": "Camera6",
            "motion": true,
            "motionTimeout": 0,
            "unbridge": true,
            "videoConfig": {
                "source": "-i rtsp:// user:pass @10.0.1.198:554/cam/realmonitor?channel=1&subtype=1"
            }
        },
        {
            "name": "Camera7",
            "motion": true,
            "motionTimeout": 0,
            "unbridge": true,
            "videoConfig": {
                "source": "-i rtsp:// user:pass @10.0.1.191:554/cam/realmonitor?channel=1&subtype=1"
            }
        }
    ],
    "platform": "Camera-ffmpeg"
}

DAHUA-ALERTS

{
    "host": "10.0.1.13",
    "user": "user",
    "pass": "pass",
    "homebridgeCameraFfmpegHttpPort": 8088,
    "useHttp": false,
    "cameras": [
        {
            "index": 0,
            "cameraName": "Camera1",
            "cameraCredentials": {
                "host": "10.0.1.185",
                "user": "user",
                "pass": "pass",
                "useHttp": true
            }
        },
        {
            "index": 0,
            "cameraName": "Camera2",
            "cameraCredentials": {
                "host": "10.0.1.186",
                "user": "user",
                "pass": "pass",
                "useHttp": true
            }
        },
        {
            "index": 0,
            "cameraName": "Camera3",
            "cameraCredentials": {
                "host": "10.0.1.187",
                "user": "user",
                "pass": "pass",
                "useHttp": true
            }
        },
        {
            "index": 0,
            "cameraName": "Camera4",
            "cameraCredentials": {
                "host": "10.0.1.188",
                "user": "user",
                "pass": "pass",
                "useHttp": true
            }
        },
        {
            "index": 0,
            "cameraName": "Camera5",
            "cameraCredentials": {
                "host": "10.0.1.189",
                "user": "user",
                "pass": "pass",
                "useHttp": true
            }
        },
        {
            "index": 0,
            "cameraName": "Camera6",
            "cameraCredentials": {
                "host": "10.0.1.198",
                "user": "user",
                "pass": "pass",
                "useHttp": true
            }
        },
        {
            "index": 0,
            "cameraName": "Camera7",
            "cameraCredentials": {
                "host": "10.0.1.191",
                "user": "user",
                "pass": "pass",
                "useHttp": true
            }
        }
    ],
    "platform": "dahua-alerts"
}



________________________________

**Comment by woodgieboodgie** [comment]
Do you see an issue with the Config?

**Comment by kushagharahi** [comment]
I do not, can you try to enable debug logs and send any relevant dahua-alert logs that come up?

**Comment by woodgieboodgie** [comment]
The NVR is in the config but also there is camera override.

Qn: does https need to be enabled for plug-in to work? Or if I tell each cam to operate on http will that suffice?
I only ask as the Dahua cam wants an SSL cert installed and configured ..

On 5 Oct 2022, at 2:26 pm, Kusha Gharahi ***@***.***> wrote:

﻿

@woodgieboodgie<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwoodgieboodgie&data=05%7C01%7C%7Cc91a688deb574e936b1a08daa681542e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638005371654390427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MgIr9wXo6objKRPZlx3m6ja5UDITK%2FSgUArGhwTh8qo%3D&reserved=0> Sorry about that, are your cameras connected to your NVR?

**Comment by kushagharahi** [comment]
Without debug logs there's not much I can do to help you, sorry.
