### ISSUE TITLE
Anyone have luck getting this to work with the basic older mpx dahua DVRs like the X51A3E?

### ISSUE THREAD

**Issue by mofitn3577** [kushagharahi/homebridge-dahua-alerts#41]
Just wondering if anyone has had success with this. I see mostly just NVR systems and the newest versions of the MPX DVRs which have a lot of new features. I haven't had any luck yet and time is valuable so just trying to evaluate if it's doable and worth putting a few more hours into it or if these older basic MPX DVRs are lacking something that enables this to work with the other models listed. Thank you.

**Comment by kushagharahi** [comment]
It will almost certainly work with your X51A3E as it has ONVIF (How this plugin communicates with the NVR/Cameras)

<img width="977" alt="image" src="https://user-images.githubusercontent.com/3326002/205167888-9addb93c-a5cd-42df-982d-ce5975f89fd8.png">
