### ISSUE TITLE
Not receiving motion alerts on 1.3.0

### ISSUE THREAD

**Issue by irctrakz** [kushagharahi/homebridge-dahua-alerts#59]
Something is def not working correctly with 1.3.0, I'm not receiving any motion alerts - in fact the logs show no events at all, despite the camera for sure recording them. I'm a bit at a loss how best to support debugging (since nothing is actually happening). Happy to provide any data that would be helpful.

**Comment by irctrakz** [comment]
Ok, figured it out. For events to be correctly sent, the default for standalone cameras should be:

```
    "eventTypes": {
        "VideoMotion": true,
        "AlarmLocal": true,
        "CrossLineDetection": true
    },
  ```

**Comment by irctrakz** [comment]
I would propose the docs need to be updated or this is going to catch folks out

**Comment by kushagharahi** [comment]
@indoctrine contributed this readme update, thanks both!
