### ISSUE TITLE
Only camera without NVR

### ISSUE THREAD

**Issue by absentvs** [kushagharahi/homebridge-dahua-alerts#6]
Hello! What about the ability to config Dahua camera without using NVR.

**Comment by kushagharahi** [comment]
Hi @absentvs

Without owning the device myself I can not check if it works. Please install the plug-in and post a new issue with debug logs.

**Comment by absentvs** [comment]
I was able to set up one of my Dahua cameras without using an NVR by following this tutorial. And the motion sensor for this camera works. Perfectly!
I would like to connect other cameras in the same way. But in the config I can only register one host = one camera.

**Comment by absentvs** [comment]
Attach part of the config:

 {
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "IPC151"
                }
            ],
            "host": "192.168.1.151",
            "user": "admin",
            "pass": "23091980q",
            "homebridgeCameraFfmpegHttpPort": 8088,
            "platform": "dahua-alerts"
        }

there 192.168.1.151 - IP of camera

**Comment by kushagharahi** [comment]
Hmmm ok. I understand the issue. I will take a look to see what I can do. I deleted your comment so your password wouldn’t be exposed. What Dahua stand-alone cameras are you using?

**Comment by absentvs** [comment]
Thank you!
Model DH-IPC-HDBW4631R-S

**Comment by kushagharahi** [comment]
Ok, try this, replace the dist folder contents in homebridge\node_modules\homebridge-dahua-alerts\dist with the contents of this zip. Add the required config and then restart homebridge.

[dist.zip](https://github.com/kushagharahi/homebridge-dahua-alerts/files/5752561/dist.zip)

To define a host/user/pass on a camera simply add the `cameraCredentials` object. If you have a top level host/user/pass defined, this object will override it. 
```
    "cameras": [
        {
            "index": 0,
            "cameraName": "Driveway"
            "cameraCredentials": {
                    "host": "XX.XX.XX.XX",
                    "user": "admin",
                    "pass": "XX"
            }
        },
```

**Comment by absentvs** [comment]
I am sorry for the long answer.
Updated all files and config.
Motion from all cameras will trigger the first camera's motion sensor in all cases.

{
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "IPC151",
                    "cameraCredentials": {
                        "host": "192.168.1.151",
                        "user": "admin",
                        "pass": "*****"
                    }
                },
                {
                    "index": 1,
                    "cameraName": "IPC152",
                    "cameraCredentials": {
                        "host": "192.168.1.152",
                        "user": "admin",
                        "pass": "*****"
                    }
                }
            ],
            "homebridgeCameraFfmpegHttpPort": 8088,
            "platform": "dahua-alerts"
        }

**Comment by kushagharahi** [comment]
Awesome, thanks for testing. Ok I think I've solved the problem but you have to test it again. 
[dist.zip](https://github.com/kushagharahi/homebridge-dahua-alerts/files/5756060/dist.zip)

**Comment by absentvs** [comment]
Great, now it works correctly! Thank you so much!
But there is one config caution. All cameras works independently and therefore the index must be 0 for all cameras:

             "cameras": [
                 {
                     "index": 0,
                     "cameraName": "IPC151",
                     "cameraCredentials": {
                         "host": "192.168.1.151",
                         "user": "admin",
                         "pass": "xxx"
                     }
                 },
                 {
                     "index": 0,
                     "cameraName": "IPC152",
                     "cameraCredentials": {
                         "host": "192.168.1.152",
                         "user": "admin",
                         "pass": "xxx"
                     }
                 }

If one of cameras index not 0 , then trigger for this camera is not answer.

**Comment by kushagharahi** [comment]
Awesome! Happy to hear that. I just pushed this update. Do you mind updating to version `1.1.0` and making sure that works too?

**Comment by kushagharahi** [comment]
I made a note in the readme about standalone camera index :) good tip.

**Comment by absentvs** [comment]
version 1.1.0 works similarly!

**Comment by kushagharahi** [comment]
Awesome thanks! If you run into any other problems don't hesitate to open another issue :D
