### ISSUE TITLE
 Error Details: Didn't get a response from the NVR - connect ECONNREFUSED

### ISSUE THREAD

**Issue by erickkowalski** [kushagharahi/homebridge-dahua-alerts#8]
Hello 

i have a problem making this plugin to work 

i have checked all the ip hosts, ports and user credentials still it comes back with the following error 

[dahua-alerts] Error Received (for more info enable debug logging)
[dahua-alerts] Error Details: Didn't get a response from the NVR - connect ECONNREFUSED 192.168.0.20:443
[dahua-alerts] Reconnecting in 10s.

config code:

"name": "Camera FFmpeg",
            "porthttp": 8088,
            "localhttp": true,
            "cameras": [
                {
                    "name": "front",
                    "motion": true,
                    "switches": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://xxx",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 574,
                        "maxFPS": 20,
                        "maxBitrate": 293,
                        "vcodec": "h264_omx",
                        "packetSize": 188
                    }
                },
                {
                    "name": "garden",
                    "motion": true,
                    "switches": true,
                    "motionTimeout": 0,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i xxx",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 574,
                        "maxFPS": 20,
                        "maxBitrate": 293,
                        "vcodec": "h264_omx",
                        "packetSize": 188
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
      
        {
            "cameras": [
                {
                    "index": 0,
                    "cameraName": "front"
                },
                {
                    "index": 1,
                    "cameraName": "garden"
                }
            ],
            "host": "192.168.0.20",
            "user": "xxx",
            "pass": "xxx",
            "homebridgeCameraFfmpegHttpPort": 8088,
            "platform": "dahua-alerts"
        },

the camera ffmpeg plugin work fine 

Any advise?

Ps Sorry for the previous message 

cheers Erick

**Comment by kushagharahi** [comment]
Were you able to get it working @erickkowalski ? Is that why you closed this?

**Comment by erickkowalski** [comment]
Yes 

I had to enable 443 port on the nvr 

Thanks 

Erick Kowalski

**Comment by kushagharahi** [comment]
Yay awesome! Glad to hear it and thanks for sharing what the fix is.

Do you mind sharing the model number of your NVR so I can put it in the readme?

**Comment by erickkowalski** [comment]
No Problem 


Nvr model: Dahua DHI-NVR4104HS-P-4Ks2

I’ve got 2 caneras 1 of them motion detect works ok 
The 2nd one is not changing the status 
Dunno why 
Will let you know if figured it out 



Erick Kowalski
